### ISSUE TITLE
Mitella/Pectiantia ovalis

### ISSUE THREAD

**Issue by japonicus** [BSBI/mapmate-taxon-requests#1]
request via email from Stephen Bungard
> We have this growing in the wild on Skye. Looks like a first for the British Isles – though seed is available in the UK for gardeners e.g. http://www.growildnursery.co.uk/store/p26/Mitella_ovalis__Bishops_Cap_%2F_Oval-leaved_Mitrewort.html

Am uncertain of the accepted genus, Stephen proposes Pectiantia, per http://biology.burke.washington.edu/herbarium/imagecollection.php?ID=5182 but other sources are divided.

Both names are accepted in theplantlist [Mitella ovalis](http://www.theplantlist.org/tpl1.1/record/tro-29100137) / [Pectiantia ovalis](http://www.theplantlist.org/tpl1.1/record/tro-29100932)

[ DDb has both (newly added with no records)](https://database.bsbi.org/search.php#retrievesaved=0.32snq&query=f5a27a0a5d4b450194d67ed62a29f6a0), with Mitella as the accepted (but this could be revised)

Neither name is in MapMate

**Comment by sacrevert** [comment]
I agree with your decision. Mitella ovalis is accepted in the [FNA Vol.8 (2009)](http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250065979), so, seems reasonable to go with this in the absence of specialist advice.

**Comment by tangiblegains** [comment]
Gordon Young has just requested Mitella ovalis be added to MM - found in South Northumberland.

**Comment by japonicus** [comment]
Stace 4 names will all be included
