### ISSUE TITLE
Primula prolifera

### ISSUE THREAD

**Issue by kwal2** [BSBI/mapmate-taxon-requests#12]
Ted Pratt first recorded this for GB in Dorset in 2006 (there are subsequent records for Cornwall in DDb). It needs adding to MM so that Robin Walls can submit the record:

Hello Kevin
I see you have not been told of the first record of this.
It was made by Steve O’Connell, a National Trust Ranger, who showed it to me in 2006, at SZ03468330, in a stream beyond the south end of Knoll Beach car park. It was determined by Eric Clement as P. helodoxa, it old name. There were 58 plants. They are much reduced now due to shading.
They had almost certainly been washed downstream from a garden by a cloudburst the previous autumn.
Best wishes – Ted P

**Comment by japonicus** [comment]
Stace 4 names will all be included
