### ISSUE TITLE
Viola labradorica misapplied to purple horticultural forms of V. riviniana ?

### ISSUE THREAD

**Issue by japonicus** [BSBI/mapmate-taxon-requests#19]
Not strictly a MapMate question...

The DDb has 16 records for Viola labradorica Schrank (brc concept Vas_4090)

according to wikipedia (the ultimate font-of-all-knowledge 🙂 ) [V. labradonica is misapplied to horticultural origin V. riviniana group 'Purpurea'](https://en.wikipedia.org/wiki/Viola_labradorica)

This is certainly the case for the Cambridge DDb record from TL451575 which is ex-Plant Records, where it is listed as **hort. non Schrank.** http://archive.bsbi.org.uk/Wats24p539.pdf

should Vas_4090 be changed to hort. non Schrank. and perhaps synonymised with V. riviniana group 'Purpurea' or are there also valid records for the name.

**Comment by sacrevert** [comment]
I agree that this is very the likely situation (most of the refs given in Clement and Foster (1994) for this taxon are horticultural dictionaries), but it is difficult to make a blanket decision without doing more research. Would it be worthwhile delegating this decision to the referees/recent handbook authors? However, if you are seeking to minimise this type of additional consultation, then I would be happy to be a bit of extra digging as I have time.

**Comment by japonicus** [comment]
Thanks.

> Would it be worthwhile delegating this decision to the referees/recent handbook authors?

yes, that would probably be best.

There's no urgency - I filed the bug mostly as marker that there was a problem (having noticed the issue while preparing a dataset for import) rather than as something requiring immediate attention.

**Comment by sacrevert** [comment]
Having looked at the Viola handbook at home last night, I think your suggested plan of synonymy is fine. V. labradorica is only mentioned in the handbook in the context of being misreported for V. riviniana group 'Purpurea', whereas other recorded garden escapes are treated in full.
