### ISSUE TITLE
Amaranthus sp.

### ISSUE THREAD

**Issue by GeoffToone** [BSBI/mapmate-taxon-requests#23]
I have an as yet undetermined record for an Amaranth which might be either A. cruentus or hypochondriacus. A place holder until it can be sampled (it's on private land) seems the best approach.

**Comment by japonicus** [comment]
Amaranthus is already in mapmate (vp0201z1).

**Comment by GeoffToone** [comment]
Sorry Tom, you're quite right, I'd forgotten this one had been dealt with.
