### ISSUE TITLE
Oenothera parviflora L.

### ISSUE THREAD

**Issue by tangiblegains** [BSBI/mapmate-taxon-requests#3]
A specimen of Oenothera parviflora was sent to and confirmed by Rose Murphy (BSBI referee for this genus). It was found by George Hounsome and Eric Clement at Barnes Station, Waste Ground (TQ223756) in 2011. The taxon is included in Stace (2010), but apparently not in MapMate. I do not have access to MM, so cannot verify this assertion. In the BSBI Handbook, RM states that "O. cambrica used to be confused with O. parviflora", and I note that O. parviflora auct., non L. is a synonym of O. cambrica in the DDb.  Assuming that a check of the MM dictionary finds that Oenothera parviflora L. is not included, I think it's reasonable to add it to the dictionary.

**Comment by sacrevert** [comment]
Agreed. Sell & Murrell Vol 4 list it stating "Introduced. Locally plentiful in a chalkpit at Stone in Kent and a few other records as a casual although some are referable to O. cambrica. Native of eastern North America. apparently now utilised as a crop for oil."

**Comment by japonicus** [comment]
Stace 4 names will all be included
