### ISSUE TITLE
Atriplex micrantha Ledeb.    Asian Orache

### ISSUE THREAD

**Issue by DavidBroughton** [BSBI/mapmate-taxon-requests#32]
Alien Plants of Yorkshire gives several records for VC63 & 64. Most by F. Houseman who sent material to Kew for identification/verification. On this basis, no reason to doubt validity of records. VC records not currently captured in DDB.  DDB species entry at https://database.bsbi.org/object.php?entityid=2cd4p9h.3hkdgg&class=TaxonInstance

**Comment by sacrevert** [comment]
This merely to note that very few records from Wilmore's Alien Plants of Yorkshire are in the DDb. A digitisation job for someone with some free time!

**Comment by japonicus** [comment]
Also requested by Geoffrey Kitchener, who has added several records for Kent.

**Comment by japonicus** [comment]
Stace 4 entries will be included
