### ISSUE TITLE
Allium trifoliatum Cyrillo

### ISSUE THREAD

**Issue by TonyMundell** [BSBI/mapmate-taxon-requests#47]
See BSBI News133 p.30. I now have several VC12 records for this and is pretty clear that many British records for Allium subhirsutum are errors for A. trifoliatum. To reduce the chance of more erroneous records accumulating A. trifoliatum needs adding to the taxa list for both MapMate and the DDB.

**Comment by japonicus** [comment]
I've added this to the DDb: https://database.bsbi.org/object.php?entityid=2cd4p9h.f8ry79&class=TaxonInstance

**Comment by japonicus** [comment]
Stace 4 taxa will be included.
