### ISSUE TITLE
Soliva valdiviana

### ISSUE THREAD

**Issue by GeorgeHBSBI** [BSBI/mapmate-taxon-requests#5]
Soliva valdiviana Phil.

Found in VC 17 at Ripley and on a derelict golf course in Hounslow VC21

Already on the DDb but not in MapMate

**Comment by martinrand** [comment]
Given this is turning up in other VCs (mine included), it would be nice to see action on this.

**Comment by japonicus** [comment]
Will be added as Stace 4 Cotula sessilis
