### ISSUE TITLE
Utricularia intermedia agg.

### ISSUE THREAD

**Issue by tangiblegains** [BSBI/mapmate-taxon-requests#6]
Mapmate has two options for recording U. intermedia: U. intermedia s.l. or s.s.. Recent BSBI notes and publications recommend recording Utricularia intermedia agg. if unsure of identification, as the segregates U. intermedia s.s., U. ochroleuca and U. stygia can be difficult to separate vegetatively.  Paul Green has asked for the agg. to be added to Mapmate, as he feels that most recorders do not understand the difference between s.s. and s.l., and so may, by default, record s.s.  I'd be interested in your thoughts on this - I had originally responded to Paul stating that we could simply subsume s.l. records into the aggregate, but perhaps this is not the way to do it, and we run the risk of spurious s.s. records finding their way into the database?

**Comment by japonicus** [comment]
What is U. intermedia s.l. meant to mean? (does it have a set of segregates distinct from those in the agg.)

MapMate's "U. intermedia s.l." is currently mapped to U. intermedia agg. in the DDb (which is defined, as you described, including U. intermedia s.s., U. ochroleuca and U. stygia).

There are several cases where MapMate uses s.l. in cases where agg. may be the more appropriate term.

**Comment by sacrevert** [comment]
U. intermedia s.l. is synonymous with the agg., at least in terms of what was defined in the VPDB and what is now given for the agg. in the DDb. I don't think it is possible to have a view on what is more appropriate in any technical sense, only a view on what is most useful and intuitive to recorders. Given that the 'Notes on identification...' etc. give U. intermedia agg., it would probably also be useful to have this in Mapmate as well. 

(I don't know how Mapmate works, so whether this would further confuse people by providing two options, or whether the s.l. concept would subsequently be hidden from view as a synonym of the agg., I cannot say).

**Comment by tangiblegains** [comment]
Yes, my fear was that adding an agg, to the s.l. option would simply serve to confuse. I think we either add the agg. and hide s.l., or do nothing.

**Comment by japonicus** [comment]
I think it would be a matter of renaming "U. intermedia s.l." to "U. intermedia agg." in mapmate (the alternative would be add 'agg' and set the 's.l.' as a non-preferred synonym - which seems unnecessarily complex)

I'm unsure which term is technically better, in the DDb I've used 's.l.' for aggregates resulting from the splitting of a name and 'agg.' where the components are less obviously linked by a taxonomic revision (and instead reflect a grouping that reflected recording conventions or id difficulties).
By those criteria the U. intermedia broad concept would be "s.l." if it only included ochroleuca (by virtue of the past splitting of Utricularia intermedia f. ochroleuca; or the synonymy of Utricularia intermedia auct., non Hayne) but the additional inclusion of stygia (which doesn't appear to have a taxonomic cause) makes it an "agg."

I'm not sure that my definition of the distinction between s.l. and agg. is correct - it seemed the best match for the way that BSBI was using the terms and at least lead to some consistency.

At present, for practical purposes the DDb treats 's.l.' and 'agg.' keywords as absolutely interchangeable for searching or taxon matching purposes.

**Comment by sacrevert** [comment]
It sounds like it would be worth doing then.

I don't think either one is technically better in the sense that we are using them for biological recording. Your definition is certainly defensible, but it is not a widely agreed standard (you could argue that U. stygia was implicitly included within one of the other concepts in the past, and therefore fits within your definition of a taxonomic change). There is technical guidance on the use of _sensu_ in the current Code, but as far as I can see this should technically be linked to an author. Anyway, I think your usage, and the fact that the DDb treats them as synonymous, are both fine for recording purposes.

**Comment by japonicus** [comment]
After the update, MapMate will follow DDb names, so the MapMate s.l. entry will be renamed to agg.
