### ISSUE TITLE
Viola palustris subsp. palustris L.

### ISSUE THREAD

**Issue by TonyMundell** [BSBI/mapmate-taxon-requests#64]
On   MapMate V. palustris is given as Marsh Violet but curiously V. palustris   subsp. palustris is given as Bog Violet. 'Stace 3' uses Marsh Violet
--

**Comment by japonicus** [comment]
The MapMate name will be updated to follow Stace ed. 4 ('Marsh Violet' at sp level and no separate subsp vernacular).
