### ISSUE TITLE
X Conyzigeron stanleyi Mundell

### ISSUE THREAD

**Issue by TonyMundell** [BSBI/mapmate-taxon-requests#65]
I originally named this in New Journal of Botany 2016 Vol.6 No.1. and predicted that it was likely to be found in many other places. The latest I have heard about was at Burry Port, the site of the former Camarthen Bay Power Station, by Barry Stewart (VC41 Recorder) on 17 Sep 2018, det. Tim Rich. It was re-named in Journal of New Botany Vol.7 No.1 as Erigeron x stanleyi (Mundell) Mundell but I guess that for now there will be a preference to keep Conyza and X Conyzigeron separate from Erigeron to follow Stace 3rd editon rather than the forthcoming 4th edition. It is not on the DDb or MapMate but I want to record it, ideally on MapMate. A record for it in 2018 was sent to me from the original Winchester site. It is frustrating not being able to record it.

**Comment by TonyMundell** [comment]
I also found this plant growing with both parents in Bordon VC12 on 20 Oct2018. I strongly suspect that because it is not available on MapMate this hybrid is being mis-recorded either as the very similar X Conyzigeron huelsenii (Erigeron acris x Conyza canadensis) or as Erigeron acris x Conyza sumatrensis (both of which are on the MapMate taxa list).

**Comment by kwal2** [comment]
For now this should be enterred on the DDb and Mapmate as the intergeneric hybrid between Erigeron acris and Conyza floribunda although note that all Conyza will be placed in Erigeron in Stace (2019). Therefore the taxon will need changing to the new published name of Erigeron x stanleyi (A.R.G.Mundell) Mundell when Stace Ed4 changes are implemented.

**Comment by TonyMundell** [comment]
Tom,

That is sensible but the point I am trying to make is that the hybrid (that
I named) between Erigeron acris and Conyza floribunda is not available on
the MapMate taxa list so I cannot record it.

I see that it has now appeared on the DDB taxa list so thanks for that.
However I would far prefer to have all Hampshire records available on my
local MapMate Hampshire database (from whence they get synched to the DDB)
so that I can display records on the local maps I have set up for all
Hampshire and various Nature Reserves etc. I prefer not to enter records
direct on the DDB bypassing my MapMate database.

I cannot see the logic of having taxa available on the DDB that are not
also on the MapMate taxa list.

Incidentally I heard very recently from Paul Stanley that he has found  X
Conyzigeron stanleyi (= Erigeron x stanleyi) at two sites on the Isle of
Wight. (I named this hybrid after Paul). I am sure this hybrid is pretty
common wherever the parents occur. It turned up in two places in North
Hampshire this year. What concerns me is that MapMate users will be
recording it in error for the other two very similar hybrids that are
available on MapMate, X Conyzigeron huelsenii (= Conyza canadensis x
Erigeron acris) or Conyza sumatrensis x Erigeron sumatrensis.

Tony Mundell

**Comment by japonicus** [comment]
Hi Tony,

Kevin's comment related to the planning for a MapMate update in January (when for the sake of consistency the taxon would be listed as X Conyzigeron stanleyi ) followed by a further update later when Stace 4 names are adopted.

I agree with you about the urgency of the MapMate update due to the potential for  loss of records, or miss-recording - but as a short-term solutions we always encourage records to submit records for taxa not in MapMate directly for DDb inclusion.

The reason names are added to the DDb more rapidly than to MapMate, is that the process to do that is simpler and far quicker.  Nationally, between 15 - 20% of BSBI's recent records come from sources other than MapMate.

**Comment by japonicus** [comment]
All Stace 4 names (including this) will be added to MapMate.
